### PR TITLE
New Transformer methods to support dynamic replacement strings such a…

### PR DESCRIPTION
**Pull request by jshenguru**
In conjunction with [this replace-response PR](https://github.com/caddyserver/replace-response/pull/34). Details are in the comment lines of the added methods.

### CODE REVIEW

**Comment by icholy** [comment]
Since these functions are specific to Caddy's replace-response module's needs, would it make more sense to implement them directly in that project instead of adding them to this general-purpose library?

**Comment by jshenguru** [comment]
I have encountered wide variety of applications that requires such "late binding" feature. In my Modbus driver, the data conversion formula is based on a ratio which is read from a instrument during runtime and that ratio setting in the instrument changes from time to time. In almost all of my web applications, UI language is obtained from user's preference and the preference changes from user to user and change from time to time. All those use cases requires the `template` and the `new` in the replace transformer to bear some "macro" or "placeholder" which can only be substantiated at the moment of applying the transformer.

**Comment by icholy** [comment]
But these functions are not adding any new functionality. They're just a new API to do something that was already relatively simple with the existing API.

**Comment by icholy** [comment]
I also really don't understand the point of `StringWithLateBinding`, it doesn't do anything. Is this AI generated code because it doesn't really make any sense?

**Comment by jshenguru** [comment]
> I also really don't understand the point of `StringWithLateBinding`, it doesn't do anything. Is this AI generated code because it doesn't really make any sense?

Please take a look at [this PR in the caddyserver/replace-response](https://github.com/caddyserver/replace-response/pull/34/commits) to understand why this late binding method is needed.

**Comment by icholy** [comment]
This code should be added directly to the linked PR.

**Comment by jshenguru** [comment]
@mholt Please advise how we should go about enabling placeholders in the caddyserver/replace-response package.

**Pull request closed without merging**
